게시글 및 댓글 수정사항 반영
team-forAdhd/forAdhd-server pull request #47
Opened 2024-07-23 11:38 UTC by newoceanwave

## 💻 구현 내용 

- `postserviceimpl`, `commentserviceimpl `내 레포지토리 네이밍 변경
- `getPost`, `getComment` 메서드 사용하여 중복되는 코드 수정
- **commentserviceimpl**에서 
`@Override
    @Transactional
    public void deleteComment(Long commentId) {
        Comment comment = commentRepository.findById(commentId)
                .orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOUND_COMMENT));

        // 원댓글에 연결된 대댓글의 부모 참조를 null로 설정
        List<Comment> childComments = commentRepository.findByParentCommentId(commentId);
        for (Comment childComment : childComments) {
            childComment.setParentComment(null);
            commentRepository.save(childComment);
        }

        // 원 댓글 삭제
        commentRepository.deleteById(commentId);
    }

    @Transactional
    public void deleteChildrenComment(Long commentId) {
        commentRepository.deleteByParentId(commentId);
    }` 로 부모댓글과 자식댓글 삭제를 따로따로 구현하도록 변경했습니다.

- 다은님께서 작성해주신 paging 기반으로 responsedto를 변경했습니다.
`@Getter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PostResponseDto {

    private List<PostListResponseDto> postList;
    private PagingResponse paging;

    @Getter
    @Builder
    @AllArgsConstructor
    @NoArgsConstructor
    public static class PostListResponseDto {
        private Long id;
        private String userId;
        private String title;
        private String content;
        private boolean anonymous;
        private List<String> images;
        private long likeCount;
        private long commentCount;
        private long scrapCount;
        private long viewCount;
        private CategoryName category;
        private List<CommentResponseDto.CommentListResponseDto> comments; // 수정된 부분
        private String nickname;
        private String profileImage;

        @JsonSerialize(using = LocalDateTimeToEpochSecondSerializer.class)
        private LocalDateTime createdAt;
        @JsonSerialize(using = LocalDateTimeToEpochSecondSerializer.class)
        private LocalDateTime lastModifiedAt;
    }
}
`로 변경하여 응답값 다음과 같습니다. 
`{
    "postList": [
        {
            "id": 1,
            "userId": "fe57595b62334291900b48ac0f4444c0",
            "title": "10대 테스트 게시글 1 수정 제목입니다.",
            "content": "10대 테스트 게시글 1 수정 내용입니다.",
            "anonymous": false,
            "images": [
                "http://edit",
                "http://edit2"
            ],
            "likeCount": 0,
            "commentCount": 0,
            "scrapCount": 0,
            "viewCount": 0,
            "category": "TEENS",
            "comments": [],
            "nickname": "이헨",
            "profileImage": "http://",
            "createdAt": 1721706872,
            "lastModifiedAt": 1721707233
        },
        {
            "id": 2,
            "userId": "fe57595b62334291900b48ac0f4444c0",
            "title": "10대 테스트 게시글 2",
            "content": "10대 테스트 게시글 2입니다.",
            "anonymous": true,
            "images": [
                "http://ex",
                "http://ex2"
            ],
            "likeCount": 0,
            "commentCount": 0,
            "scrapCount": 0,
            "viewCount": 0,
            "category": "TEENS",
            "comments": [],
            "nickname": "익명",
            "profileImage": "http://example.com/default-profile.png",
            "createdAt": 1721706887,
            "lastModifiedAt": 1721706887
        }
    ],
    "paging": {
        "page": 0,
        "size": 20,
        "totalPages": 1,
        "numberOfElements": 2,
        "totalElements": 2,
        "isFirst": true,
        "isLast": true,
        "isEmpty": false
    }
}`

- 불필요하게 save 메서드를 호출하던 부분들을 수정했습니다. (postserviceimpl, commentserviceimpl)
 `    public Post updatePost(Post post) {
        Post existingPost = getPost(post.getId());

        Post updatedPost = existingPost.toBuilder()
                .title(post.getTitle())
                .content(post.getContent())
                .images(post.getImages())
                .build();

        return updatedPost;
    }`

- 익명으로 글 작성 시 nickname과 profileImage 다음과 같이 매핑되도록 했습니다. 
`    @AfterMapping
    default void setUserProfile(@MappingTarget PostResponseDto.PostListResponseDto.PostListResponseDtoBuilder dto, Post post, @Context UserProfileRepository userProfileRepository) {
        if (post.isAnonymous()) {
            dto.nickname("익명");
            dto.profileImage("http://example.com/default-profile.png");
        } else if (post.getUser() != null) {
            Optional<UserProfile> userProfileOptional = userProfileRepository.findByUserId(post.getUser().getId());
            userProfileOptional.ifPresent(userProfile -> {
                dto.nickname(userProfile.getNickname());
                dto.profileImage(userProfile.getProfileImage());
            });
        }
    }` 그런데 익명시 프로필 이미지를 url로 받아오는게 나을지, 아니면 db에 저장 후 불러오는 방법이 나을지는 세빈님과 논의 중에 있습니다. (결정 후 수정하겠습니다)

- 익명으로 댓글 작성 시 익명 1, 익명 2와 같이 숫자가 증가해야 하기 때문에 commentserviceimpl에 다음과 같은 메서드 구현했습니다. 
`@Override
    public String generateAnonymousNickname(Long postId, String userId) {
        List<Comment> userComments = commentRepository.findByPostIdAndUserIdAndAnonymous(postId, userId, true);
        if (!userComments.isEmpty()) {
            return userComments.get(0).getNickname();
        } else {
            long anonymousCount = commentRepository.countByPostIdAndAnonymous(postId, true);
            return "익명 " + (anonymousCount + 1);
        }
    }`

## 🛠️ 개발 오류 사항
- 알림창을 구현하기 위해 SSE 방식으로 구현하고자 했으나 엔드포인트에 접근 시 무한로딩 현상이 발생하고 있습니다.
- 관련 코드들은 다음과 같습니다. 

**1. notification.java**
`@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
@Table(name = "notification")
public class Notification {
    @jakarta.persistence.Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String userId;

    private String message;

    private boolean isRead;

    @JsonSerialize(using = LocalDateTimeToEpochSecondSerializer.class)
    private LocalDateTime createdAt;
}
`

**2. NotificationServiceImpl**
```
@Service
@RequiredArgsConstructor
public class NotificationServiceImpl implements NotificationService {
    private final NotificationRepository notificationRepository;
    private final SseEmitters sseEmitters;

    @Override
    public void createNotification(String userId, String message) {
        Notification notification = Notification.builder()
                .userId(userId)
                .message(message)
                .isRead(false)
                .createdAt(LocalDateTime.now())
                .build();
        notificationRepository.save(notification);
        sseEmitters.sendNotification(userId, message);
    }

    @Override
    public List<Notification> getNotifications(String userId) {
        return notificationRepository.findByUserIdOrderByCreatedAtDesc(userId);
    }

    @Override
    @Transactional
    public void markAsRead(Long notificationId) {
        Notification notification = notificationRepository.findById(notificationId)
                .orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOUND_NOTIFICATION));

        Notification updatedNotification = notification.toBuilder()
                .isRead(true)
                .build();

        notificationRepository.save(updatedNotification);
    }
}
```

**3. notificationcontroller**
`@RestController
@RequestMapping("/api/v1/notifications")
@RequiredArgsConstructor
@CrossOrigin(origins = {"http://localhost:3000", "http://localhost:8080"})
public class NotificationController {
    private final NotificationService notificationService;
    private final SseEmitters sseEmitters;

    @GetMapping("/sse")
    public SseEmitter streamSseMvc(@RequestParam String userId) {
        SseEmitter emitter = new SseEmitter(0L);
        sseEmitters.addEmitter(userId, emitter);
        emitter.onCompletion(() -> sseEmitters.removeEmitter(userId, emitter));
        emitter.onTimeout(() -> sseEmitters.removeEmitter(userId, emitter));
        emitter.onError((e) - [...]

2024-08-03 05:58 UTC, jkde7721 reviewed
API가 많은데도 빠르게 수정하시느라 고생많으셨습니다. 리뷰는 너무 늦어져서 죄송해요... 알림 관련해서 SSE는 처음 알게 되었는데 좀더 공부한 후 리뷰 남기겠습니다. 추가로 조금더 개선했으면 좋겠는 부분 전달드립니다!

- 게시글, 댓글 삭제 시 post_like_filter, comment_like_filter, post_scrap_filter 테이블의 FK 제약조건으로 오류가 발생하고 있습니다. 
- 전반적으로 쿼리 개선이 필요할 것 같습니다. 관련 엔티티를 fet join 등으로 조회하지 않고 각각 나눠서 쿼리하다 보니(ex. 게시글 조회 후 관련 댓글 조회 -> 하나의 쿼리로 가능) N + 1 문제가 발생하는 곳이 있습니다. 추천 드리는 방법은 spring.jpa.open-in-view=false 설정으로 OSIV 를 끈 후 LazyInitializationException 예외가 발생하는 부분부터, 직접 발생하는 쿼리를 보면서 성능을 개선시키는 것입니다. 지금 당장 급한 사항은 아니니 JPA, Querydsl 등을 좀더 공부하시고 직접 개선시켜 나가면 좋을 것 같습니다. 
- 또한 메인홈 - 게시글 랭킹순 조회, 카테고리별 랭킹순 조회 등에서 API 응답 바디 형식이 배열인 API들이 있습니다. 이러한 스펙은 페이징 관련 데이터를 추가해야 하는 경우 등 스펙 변경에 유연하지 못합니다.  아래와 같이 객체 형태로 변경해주실 수 있나요?
  ```json
  [
      {
          "id": 2,
          "userId": null,
          "title": "10대 테스트 게시글 2",
          "category": "TEENS",
          "viewCount": 10,
          "likeCount": 0,
          "createdAt": 1721706887,
          "images": [
              "http://ex",
              "http://ex2"
          ]
      }
  ]
  ```

  ```json
  {
     "category":"10대",
     "paging":{ },
     "postList":[
        {
           "id":2,
           "userId":null,
           "title":"10대 테스트 게시글 2",
           "category":"TEENS",
           "viewCount":10,
           "likeCount":0,
           "createdAt":1721706887,
           "images":[
              "http://ex",
              "http://ex2"
           ]
        }
     ]
  }
  ```
- 추가로 [게시글 이슈 코멘트](https://github.com/team-forAdhd/forAdhd-server/issues/42#issuecomment-2241079581)로도 남겼던 사안인데, `User` 엔티티에서 `UserProfile`, `UserPrivacy` 엔티티에 대한 의존으로 `User` 엔티티 조회 시 관련 엔티티들이 항상 eager 로딩되는 이슈가 있습니다. (lazy 로딩으로 설정했음에도 불구하고 `@OneToOne` 매핑에서 연관관계 주인이 아닌 엔티티 조회 시 항상 eager 로딩으로 동작 -> 하이버네이트의 lazy 로딩 동작 원리때문에 어쩔 수 없음) => `User` -> `UserProfile`, `User` -> `UserPrivacy`로의 연관관계 제거해주실 수 있나요?

2024-08-06 09:01 UTC, newoceanwave commented on src/main/java/com/project/foradhd/domain/board/business/service/Impl/PostServiceImpl.java
> +        return post;
저번에 기획측에 여쭤봤을 때는 글 접속 시마다 +1 되도록 구현해달라고 말씀하셨습니다! (제 추측으로는 초기 사용자 유입을 위해서가 아닌가..? 싶습니다. 추후에 변경될 것 같긴 해요!)

2024-08-21 02:39 UTC, newoceanwave commented on src/main/java/com/project/foradhd/global/util/SseEmitters.java
> +    private final Map<String, SseEmitter> emitters = new ConcurrentHashMap<>();
이 경우 찾아보니 redis의 pub/sub이나 분산캐시를 사용하는 것이 가장 적합한 방법이라고 합니다. 해당 관련 더 공부해보고 추가 코멘트 남기겠습니다.

2024-08-21 16:40 UTC, jkde7721 commented
https://github.com/team-forAdhd/forAdhd-server/pull/47#pullrequestreview-2208876521
- 여기서 게시글, 댓글 삭제 시 발생하는 post_like_filter, comment_like_filter, post_scrap_filter 테이블의 FK 제약조건 오류 아직 처리가 안된 것 같습니다. 
- 현재 서현님이 작성해주신 테스트 실행 시 오류가 발생합니다. 이번 PR 날리면서 변경된 메소드명이 테스트 코드에는 반영이 안되었습니다. 

@newoceanwave 수정 완료했는데 제가 발견을 못한거라면 죄송해요 한번더 확인 부탁드려요!

2024-08-21 16:52 UTC, jkde7721 commented on src/main/java/com/project/foradhd/domain/board/web/controller/PostController.java
> +    private final UserProfileRepository userProfileRepository;
Mapper에서의 Repository에 대한 의존성을 제거하기 위해 post, comment 테이블에 nickname, profile_image 컬럼을 추가하신걸까요?? 현재 게시글, 댓글 작성 시 작성자의 nickname, profileImage 값을 요청으로 안보내고 있어서 DB에 저장이 안되는 것 같습니다. 한번 확인해 주세요 

추가로 이전 기획팀에 문의했을 때 다음과 같은 답변을 받았습니다. 현재 서현님이 구현하신 기능은 게시글, 댓글 작성 당시의 작성자 정보를 저장하고 보여주고 있어 닉네임, 프로필 이미지 수정 시 변경된 닉네임, 프로필 이미지가 보이지 않습니다. 혹시 아래와 같이 구현이 어렵다면 세진님에게 한번더 문의해주시면 좋을 것 같아요
<img width="70%" src="https://github.com/user-attachments/assets/7c830673-f032-426b-b56a-355907c4200e">

2024-08-25 06:48 UTC, jkde7721 requested changes

2024-08-25 06:48 UTC, jkde7721 commented on src/main/java/com/project/foradhd/domain/board/web/controller/NotificationController.java
> +    }
p1: 해당 API 호출 시 무한 로딩 문제 발생합니다. SseEmitter 객체 생성 시 timeout 시간을 0으로 설정하였는데 이는 클라이언트-서버 간 연결이 무한히 유지됨을 의미합니다. 

timeout 값을 특정 시간(밀리초 단위)으로 설정하면, 지정된 시간 동안 아무 이벤트도 전송되지 않을 경우 클라이언트 - 서버 간 연결이 자동 종료됩니다. timeout을 0으로 설정하면, 서버에서 명시적으로 SseEmitter.complete() 메서드를 호출하지 않는 한, SseEmitter가 영구적으로 유지되며 타임아웃으로 인해 자동으로 연결이 끊어지지 않습니다. 이렇게 timeout을 0으로 설정하는 경우 서버의 리소스가 오랫동안 사용되어 서버 성능에 악영향을 줄 수 있다고 합니다. 

timeout 시간을 특정 값으로 설정해주시고 추가로 처음 연결 시 더미 이벤트를 서버 -> 클라이언트로 보내지 않으면 클라이언트의 재연결 요청 시 503 에러가 발생한다고 합니다. 아래 블로그 참고하셔서 수정 부탁드려요.
```java
//첫 연결 시 더미 이벤트 발송
emitter.send(SseEmitter.event()
            .name("dummy eventName")
            .data("dummy data")
            .reconnectTime(3000L)
            .build());
```

https://tecoble.techcourse.co.kr/post/2022-10-11-server-sent-events/

2024-08-25 06:51 UTC, jkde7721 commented on src/main/java/com/project/foradhd/domain/board/web/controller/NotificationController.java
> +    }
참고로 `timeout`은 클라이언트 - 서버 간 연결 유지 시간(서버에서 특정 이벤트 발송하지 않는 경우), `reconnectTime`은 연결 종료된 후 재연결 요청까지의 대기 시간을 의미합니다.

2024-09-06 11:46 UTC, jkde7721 approved these changes

2024-09-08 09:33 UTC, merged